# Generated by Django 5.0.4 on 2024-04-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("member_email", models.EmailField(max_length=100, unique=True)),
                ("member_password", models.CharField(max_length=100)),
                ("auth_group", models.CharField(max_length=20)),
                ("is_admin", models.BooleanField(default=False)),
                ("mem_waiting", models.BooleanField(default=False)),
                ("mem_number", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
